# Generated by Django 5.0.1 on 2024-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcatalog_supermarketproduct_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='min_order_quantity',
            field=models.IntegerField(default=0, verbose_name='Min Allowed'),
        ),
    ]
