# Generated by Django 5.0.1 on 2024-01-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcatalog_min_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcatalog',
            old_name='category',
            new_name='_category',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='description',
            new_name='_description',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='discount_percentage',
            new_name='_discount_percentage',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='min_order_quantity',
            new_name='_min_order_quantity',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='price',
            new_name='_price',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='product_id',
            new_name='_product_id',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='product_name',
            new_name='_product_name',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='quantity',
            new_name='_quantity',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='bulk_id',
            new_name='_bulk_id',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='expiry_date',
            new_name='_expiry_date',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='price',
            new_name='_price',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='product_id',
            new_name='_product_id',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='product_name',
            new_name='_product_name',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='quantity',
            new_name='_quantity',
        ),
        migrations.AlterUniqueTogether(
            name='supermarketproduct',
            unique_together={('_product_id', '_bulk_id')},
        ),
    ]
