# Generated by Django 5.0.1 on 2024-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_productcatalog__category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='_category',
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='_min_order_quantity',
            field=models.IntegerField(default=1, verbose_name='Min Allowed'),
        ),
    ]
