# Generated by Django 5.0.1 on 2024-01-29 15:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productcatalog__category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_discount_percentage',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_min_order_quantity',
            new_name='min_order_quantity',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='_expiry_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='_product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='_product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='_quantity',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='supermarketproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Production Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductBulks',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('bulk_id', models.IntegerField(verbose_name='Bulk ID')),
            ],
            options={
                'db_table': 'Product Bulk',
                'unique_together': {('product_id', 'bulk_id')},
            },
        ),
        migrations.RemoveField(
            model_name='supermarketproduct',
            name='_bulk_id',
        ),
    ]
