# Generated by Django 5.0.1 on 2024-02-20 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_delete_supplyingschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyingSchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('time', models.TimeField()),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
        ),
    ]
