# Generated by Django 5.0.1 on 2024-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyingschedule',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='supplyingschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
