# Generated by Django 5.0.1 on 2024-02-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category__description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='_name',
            new_name='name',
        ),
    ]
