# Generated by Django 5.0.1 on 2024-03-12 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0006_alter_user_session_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWallet",
            fields=[
                (
                    "wallet_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Balance"
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.retailer",
                        verbose_name="Retailer",
                    ),
                ),
            ],
            options={
                "db_table": "Payment Wallet",
            },
        ),
    ]
