# Generated by Django 5.0.1 on 2024-05-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentwallet", "0004_alter_paymentwallet_balance"),
        ("user", "0007_user_auth_provider_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentwallet",
            name="retailer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.retailer",
                verbose_name="Retailer",
            ),
        ),
    ]
