# Generated by Django 5.0.1 on 2024-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoOrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunt_reach_level', models.IntegerField(default=0, verbose_name='Reach Level')),
                ('ordering_amount', models.IntegerField(verbose_name='Ordering Amount')),
                ('confirmation_status', models.BooleanField(default=False, verbose_name='Requires Confirmation')),
            ],
            options={
                'db_table': 'Auto Ordering Config',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_status', models.BooleanField(default=True)),
                ('near_expiry_days', models.IntegerField()),
                ('low_quantity_threshold', models.IntegerField()),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App')], max_length=10)),
            ],
            options={
                'db_table': 'Notification Config',
            },
        ),
    ]
