# Generated by Django 5.0.1 on 2024-04-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('user', '0007_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='retailer',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='user.retailer', verbose_name='Retailer'),
            preserve_default=False,
        ),
    ]
