# Generated by Django 5.0.1 on 2024-04-21 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_notificationconfig_retailer'),
        ('product', '0012_productbulk_days_to_expiry'),
        ('user', '0007_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorderconfig',
            name='products',
            field=models.ManyToManyField(to='product.supermarketproduct'),
        ),
        migrations.AddField(
            model_name='autoorderconfig',
            name='retailer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user.retailer', verbose_name='Retailer'),
            preserve_default=False,
        ),
    ]
