# Generated by Django 5.0.1 on 2024-04-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_autoorderconfig_products_autoorderconfig_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoorderconfig',
            name='retailer',
        ),
    ]
