# Generated by Django 5.0.1 on 2024-04-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_autoorderconfig_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoorderconfig',
            name='products',
        ),
    ]
