# Generated by Django 5.0.1 on 2024-04-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_remove_autoorderconfig_products'),
        ('user', '0007_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorderconfig',
            name='retailer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.retailer', verbose_name='Retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoorderconfig',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('SPECIAL', 'Special')], default='DEFAULT', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='notificationconfig',
            unique_together={('retailer', 'notification_method')},
        ),
    ]
