# Generated by Django 5.0.1 on 2024-05-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_autoorderconfig_ordering_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notificationconfig',
            name='notification_method',
        ),
    ]
