# Generated by Django 5.0.1 on 2024-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_notificationconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoorderconfig',
            name='ordering_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordering Amount'),
        ),
        migrations.AlterField(
            model_name='autoorderconfig',
            name='qunt_reach_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Reach Level'),
        ),
    ]
