# Generated by Django 5.0.1 on 2024-02-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commercial_reg',
            field=models.ImageField(blank=True, null=True, upload_to='comm_reg_imgs/', verbose_name='commercial register'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/', verbose_name='profile picture'),
        ),
    ]
