# Generated by Django 5.0.1 on 2024-02-20 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username_user_session_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='supplyingschedule',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier'),
        ),
        migrations.DeleteModel(
            name='RetailerProfile',
        ),
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
