# Generated by Django 5.0.1 on 2024-02-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_supplierprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyingSchedule',
        ),
    ]
