# Generated by Django 5.0.1 on 2024-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_supplyingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_token',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
