# Generated by Django 5.0.1 on 2024-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('RETAILER', 'Retailer'), ('UNDEFIEND', 'Undefined')], max_length=50),
        ),
    ]
