# Generated by Django 5.0.1 on 2024-05-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_token',
        ),
    ]
