# Generated by Django 5.0.1 on 2024-04-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.IntegerField(editable=False, unique=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.retailer')),
            ],
            options={
                'db_table': 'HardwareSet',
            },
        ),
    ]
