# Generated by Django 5.0.1 on 2024-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareset',
            name='gateway_id',
            field=models.IntegerField(editable=False),
        ),
    ]
