# Generated by Django 5.0.1 on 2024-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_set', '0002_alter_hardwareset_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareset',
            name='gateway_id',
            field=models.IntegerField(),
        ),
    ]
