# Generated by Django 5.0.1 on 2024-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_set', '0004_alter_hardwareset_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareset',
            name='gateway_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
