# Generated by Django 5.0.1 on 2024-03-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_cartitem_cart_products'),
        ('user', '0005_delete_supplyingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.retailer'),
        ),
    ]
