# Generated by Django 5.0.1 on 2024-03-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'id')},
        ),
    ]
