# Generated by Django 5.0.1 on 2024-03-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartitem_price_cartitem_subtotal'),
        ('product', '0002_alter_productbulks_expiry_date_and_more'),
        ('user', '0005_delete_supplyingschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('cart_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'cart')},
        ),
    ]
