# Generated by Django 5.0.1 on 2024-03-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
