# Generated by Django 5.0.1 on 2024-04-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_order_order_status_delete_ordereditem"),
        ("product", "0003_alter_productcatalog_product_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="ordered_items",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_quantity",
                    models.PositiveIntegerField(verbose_name="Quantity"),
                ),
                ("item_status", models.CharField(max_length=20)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcatalog",
                    ),
                ),
            ],
            options={
                "db_table": "Order Item",
                "unique_together": {("order_id", "product_id")},
            },
        ),
    ]
