# Generated by Django 5.0.1 on 2024-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_remove_order_ordered_items_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("ready_for_delivery", "ready for delivery"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
