# Generated by Django 5.0.1 on 2024-04-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_alter_orderitem_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
    ]
