# Generated by Django 5.0.1 on 2024-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('SMART', 'SMART')], default='BASIC', max_length=20),
            preserve_default=False,
        ),
    ]
