# Generated by Django 5.0.1 on 2024-04-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_cart_type'),
        ('user', '0007_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('type', 'user')},
        ),
    ]
