# Generated by Django 5.0.1 on 2024-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('SMART', 'SMART')], default='BASIC', max_length=20),
        ),
    ]
