# Generated by Django 5.0.1 on 2024-04-30 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_alter_cart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Total Price"
            ),
        ),
    ]
