# Generated by Django 5.0.1 on 2024-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0018_order_payment_session_id_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_session_id",
            field=models.CharField(max_length=255),
        ),
    ]
