# Generated by Django 5.0.1 on 2024-05-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_payment_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
