# Generated by Django 5.0.1 on 2024-02-19 23:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_rename__description_category_description_and_more'),
        ('user', '0003_remove_user_username_user_session_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('expiry_date', models.DateField(default=datetime.date.today, verbose_name='Expiry Date')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('product_img', models.ImageField(blank=True, upload_to='catalogImgs/', verbose_name='Product Image')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('min_order_quantity', models.IntegerField(default=1, verbose_name='Min Allowed')),
                ('production_date', models.DateField(default=datetime.date.today, verbose_name='Production Date')),
                ('category', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier', verbose_name='Supplier')),
            ],
            options={
                'db_table': 'Product Catalog',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('expiry_date', models.DateField(default=datetime.date.today, verbose_name='Expiry Date')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='marketProductImgs/', verbose_name='Product Image')),
                ('Retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.retailer', verbose_name='Retailer')),
            ],
            options={
                'db_table': 'Supermarket Product',
            },
        ),
        migrations.CreateModel(
            name='ProductBulks',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('expiry_date', models.DateField(default=datetime.date.today, verbose_name='Expiry Date')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('bulk_id', models.IntegerField(verbose_name='Bulk ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier', verbose_name='Brand')),
            ],
            options={
                'db_table': 'Product Bulk',
                'unique_together': {('product_id', 'bulk_id')},
            },
        ),
    ]
