# Generated by Django 5.0.1 on 2024-01-26 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('min_order_quantity', models.IntegerField(verbose_name='Min Allowed')),
            ],
            options={
                'db_table': 'Product Catalog',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('bulk_id', models.IntegerField(verbose_name='Bulk ID')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
            ],
            options={
                'db_table': 'Supermarket Product',
                'unique_together': {('product_id', 'bulk_id')},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
