# Generated by Django 5.0.1 on 2024-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbulks',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='production_date',
            field=models.DateField(verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='supermarketproduct',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
    ]
