# Generated by Django 5.0.1 on 2024-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productbulks_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcatalog",
            name="product_img",
            field=models.ImageField(
                upload_to="catalogImgs/", verbose_name="Product Image"
            ),
        ),
    ]
