# Generated by Django 5.0.1 on 2024-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productbulks_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarketproduct',
            old_name='Retailer',
            new_name='retailer',
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='product_img',
            field=models.ImageField(upload_to='catalogImgs/', verbose_name='Product Image'),
        ),
    ]
