# Generated by Django 5.0.1 on 2024-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_retailer_supermarketproduct_retailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketproduct',
            name='tag_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
