# Generated by Django 5.0.1 on 2024-04-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_supermarketproduct_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supermarketproduct')),
            ],
            options={
                'db_table': 'Product ExpiryDate',
                'unique_together': {('id', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='ProductBulks',
        ),
    ]
