# Generated by Django 5.0.1 on 2024-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename__description_productcatalog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbulks',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='productimgs/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='productimgs/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='productimgs/', verbose_name='Product Image'),
        ),
    ]
