# Generated by Django 5.0.1 on 2024-04-16 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_expirydate_delete_productbulks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBulk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('bulk_qyt', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supermarketproduct')),
            ],
            options={
                'db_table': 'Product Bulk',
                'unique_together': {('id', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='ExpiryDate',
        ),
    ]
