# Generated by Django 5.0.1 on 2024-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productbulk_delete_expirydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='supermarketproduct',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='days_to_expiry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
