# Generated by Django 5.0.1 on 2024-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcatalog_product_img'),
        ('product', '0008_remove_productcatalog_expiry_date_and_more'),
    ]

    operations = [
    ]
