# Generated by Django 5.0.1 on 2024-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_merge_20240421_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketproduct',
            name='days_to_expiry',
        ),
        migrations.AddField(
            model_name='productbulk',
            name='days_to_expiry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
