# Generated by Django 5.0.1 on 2024-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_productbulk_days_to_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbulk',
            name='days_to_expiry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
