# Generated by Django 5.0.1 on 2024-04-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_remove_autoorderconfig_products'),
        ('product', '0013_productcatalog_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketproduct',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.autoorderconfig'),
        ),
    ]
